// Generated by CoffeeScript 1.6.3
(function() {
  var NgTemplatesCompiler;

  module.exports = NgTemplatesCompiler = (function() {
    NgTemplatesCompiler.prototype.brunchPlugin = true;

    NgTemplatesCompiler.prototype.type = 'template';

    NgTemplatesCompiler.prototype.extension = 'html';

    NgTemplatesCompiler.prototype.pattern = /\.(html|jade|md|eco|hbs|handlebars)$/;

    function NgTemplatesCompiler(config) {
      var _ref, _ref1;
      this.module = ((_ref = config.plugins) != null ? (_ref1 = _ref.ng_templates) != null ? _ref1.module : void 0 : void 0) || 'app.templates';
    }

    NgTemplatesCompiler.prototype.compile = function(data, path, callback) {
      return callback(null, "(function() {\n  try {\n    // Get current templates module\n    var module = angular.module('" + this.module + "');\n  } catch (error) {\n    // Or create a new one\n    var module = angular.module('" + this.module + "', []);\n  }\n\n  module.run(function($templateCache) {\n    // Avoid __templateData from tempering with the environment\n    var define = void 0, module = void 0;\n    // The template getter: assume `__templateData` is a function\n    // returning the template content\n    " + data + "\n    // Save the template content\n    $templateCache.put('" + path + "', __templateData());\n  });\n})();");
    };

    return NgTemplatesCompiler;

  })();

}).call(this);
